# Generated by Django 3.0.5 on 2020-11-03 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('district', models.CharField(db_index=True, max_length=256)),
                ('state', models.CharField(db_index=True, max_length=256)),
                ('pincode', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('district', models.CharField(db_index=True, max_length=256)),
                ('state', models.CharField(db_index=True, max_length=256)),
                ('pincode', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('roll_number', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1)),
                ('class_name', models.CharField(db_index=True, max_length=256)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.CollegeModel')),
            ],
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.UniversityModel'),
        ),
    ]
